---
- name: 쿠버네티스 과정 플레이북
  hosts: all
  gather_facts: yes
  tasks:
  # 1) /etc/hosts 파일 설정
    - name: 1) /etc/hosts 파일 설정
      copy:
        src: files/hosts
        dest: /etc/hosts
    # 2) SELINUX 설정  
    - name: 2) /etc/selinux/config 파일 설정
      # /etc/selinux/config(SELINUX=permissive)
      # setenforce 0
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=permissive
    - name: setenforce 0 명령 수행
      command:
        cmd: setenforce 0
    # 3) 방화벽 끄기
    - name: 방화벽 서비스 내리기
      service:
        name: firewalld
        state: stopped
        enabled: no
    # 4) 필요한 패키지 설치
    - name: 필요한 패키지 설치
      yum:
        name:
          - gnome-tweaks
          - gnome-extensions-app
        state: latest
    # 5) 확장(extensions) 활성화
    - name: 스크립트 배포, ~/bin 디렉토리 생성
      file:
        path: ~/bin
        state: directory
    - name: ~/bin/extensions.sh 파일 배포
      copy:
        src: files/extensions.sh
        dest: ~/bin/extensions.sh
        mode: '0755'
    # 6) 환경 설정(~/.bashrc) 파일 배포
    - name: ~/.bashrc 파일 배포
      template:
        src: templates/bashrc.j2
        dest: ~/.bashrc

    # 7) 바탕화면 아이콘 생성
    - name: 바탕화면 아이콘 생성
      copy:
        src: "{{ item }}"
        dest: ~/바탕화면/
      with_items:
      - "/usr/share/applications/org.gnome.gedit.desktop"
      - "/usr/share/applications/org.gnome.Terminal.desktop"
    # 8) (node1/2/3) GUI -> TUI 환경으로 전환
    - name: multi-user.target으로 전환 - default.target 삭제
      file:
        path: /etc/systemd/system/default.target
        state: absent
      when: (inventory_hostname == 'node1') or (inventory_hostname == 'node2') or (inventory_hostname == 'node3')

    - name: multi-user.target으로 전환 - default-target 링크 생성
      file:
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link
      when: gui == 'false'

    - name: multi-user.target으로 전환 - 현재 상태 변경
      command:
        cmd: systemctl isolate multi-user.target
      when: gui == 'false'
